seed_start = 20                                       # starting y position for first seed line
seed_length = 300                                     # length of seed bracket lines
seed_height = 14                                      # height of seed text boxes
seed_offset = 20                                      # indent of seed text boxes
match_length = 135                                    # length of match bracket lines
match_height = 14                                     # height of match text boxes
match_offset = 3                                      # indent of match text boxes
initial_step = 25                                     # spacing of seed lines, determines vertical
                                                      #   size of entire bracket
screen_font_size = 8                                  # font size for bracket on screen
print_font_size = 10                                  # font size for bracket on paper
print_heading_size = 12                               # font size for paper headings
print_margin_x = 10                                   # print horizontal paper margin in pixels
print_margin_y = 30                                   # print vertical paper margin in pixels
print_scores_per_page = 50                            # print scores per page
print_place_weights_per_page = 6                      # print weight place winners per page
bout_bitmap_filename = 'WrestlingNerd_wdr/bout.png'   # filename of bout sheet image
icon_filename = 'WrestlingNerd_wdr/nerd16.ico'        # filename of the program icon
scores_timer_refresh_interval = 30000                 # milliseconds between score window refreshes
highlight_color = '#FFFFC1'                           # highlight color for bracket on screen
popup_color = '#FFFFC1'                               # popup color for bracket on screen
max_name_length = 18                                  # maximum length of wrestler name
max_team_length = 18                                  # maximum length of team name
no_scoring_prefix = 'JV'                              # prefix that defaults wrestler to no scoring