# -*- coding: iso-8859-1 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: WrestlingNerd.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxWindows' modules
from wxPython.wx import *
from wxPython.grid import *

# Custom source
ID_DELETE_MATCH_MENU = wxNewId()

ID_DELETE_SEED_MENU = wxNewId()
ID_DELETEMOVEUP_SEED_MENU = wxNewId()
ID_INSERTMOVEDOWN_SEED_MENU = wxNewId()
ID_SETLAST_SEED_MENU = wxNewId()
ID_SWAPUP_SEED_MENU = wxNewId()
ID_SWAPDOWN_SEED_MENU = wxNewId()

# Window functions

ID_WEIGHTS_CHOICE = 10000
ID_TEAMS_LIST = 10001

def CreateScoreFrame( parent, call_fit = True, set_sizer = True ):
    item0 = wxBoxSizer( wxVERTICAL )
    
    item2 = wxStaticBox( parent, -1, "Weight" )
    item1 = wxStaticBoxSizer( item2, wxVERTICAL )
    
    item3 = wxChoice( parent, ID_WEIGHTS_CHOICE, wxDefaultPosition, wxSize(100,-1), [], 0 )
    item1.AddWindow( item3, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item0.AddSizer( item1, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item5 = wxStaticBox( parent, -1, "Teams" )
    item4 = wxStaticBoxSizer( item5, wxVERTICAL )
    
    item6 = wxListCtrl( parent, ID_TEAMS_LIST, wxDefaultPosition, wxSize(180,300), wxLC_REPORT|wxSUNKEN_BORDER )
    item4.AddWindow( item6, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item0.AddSizer( item4, 0, wxALIGN_CENTER|wxALL, 5 )

    if set_sizer == True:
        parent.SetAutoLayout( True )
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

ID_TEXT = 10002
ID_START_CAPTION = 10003
ID_LINE = 10004

def WizardStartPanel( parent, call_fit = True, set_sizer = True ):
    item0 = wxBoxSizer( wxVERTICAL )
    
    item1 = wxStaticText( parent, ID_TEXT, "New Tournament", wxDefaultPosition, wxDefaultSize, 0 )
    item1.SetFont( wxFont( 16, wxSWISS, wxNORMAL, wxBOLD ) )
    item0.AddWindow( item1, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item2 = wxStaticText( parent, ID_START_CAPTION, "", wxDefaultPosition, wxDefaultSize, wxST_NO_AUTORESIZE )
    item0.AddWindow( item2, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item3 = wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL )
    item0.AddWindow( item3, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    if set_sizer == True:
        parent.SetAutoLayout( True )
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

ID_NAME_CAPTION = 10005
ID_NAME_TEXT = 10006

def WizardNamePanel( parent, call_fit = True, set_sizer = True ):
    item0 = wxBoxSizer( wxVERTICAL )
    
    item1 = wxStaticText( parent, ID_TEXT, "Name", wxDefaultPosition, wxDefaultSize, 0 )
    item1.SetFont( wxFont( 16, wxSWISS, wxNORMAL, wxBOLD ) )
    item0.AddWindow( item1, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item2 = wxStaticText( parent, ID_NAME_CAPTION, "", wxDefaultPosition, wxDefaultSize, wxST_NO_AUTORESIZE )
    item0.AddWindow( item2, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item3 = wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL )
    item0.AddWindow( item3, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item4 = wxStaticText( parent, ID_TEXT, "Tournament name", wxDefaultPosition, wxDefaultSize, 0 )
    item0.AddWindow( item4, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item5 = wxTextCtrl( parent, ID_NAME_TEXT, "", wxDefaultPosition, wxSize(200,-1), 0 )
    item0.AddWindow( item5, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    if set_sizer == True:
        parent.SetAutoLayout( True )
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

ID_TEAMS_CAPTION = 10007
ID_TEAMS_COMBO = 10008
ID_ADD_TEAM = 10009
ID_REMOVE_TEAM = 10010

def WizardTeamsPanel( parent, call_fit = True, set_sizer = True ):
    item0 = wxBoxSizer( wxVERTICAL )
    
    item1 = wxStaticText( parent, ID_TEXT, "Teams", wxDefaultPosition, wxDefaultSize, 0 )
    item1.SetFont( wxFont( 16, wxSWISS, wxNORMAL, wxBOLD ) )
    item0.AddWindow( item1, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item2 = wxStaticText( parent, ID_TEAMS_CAPTION, "", wxDefaultPosition, wxDefaultSize, wxST_NO_AUTORESIZE )
    item0.AddWindow( item2, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item3 = wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL )
    item0.AddWindow( item3, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item4 = wxBoxSizer( wxHORIZONTAL )
    
    item5 = wxComboBox( parent, ID_TEAMS_COMBO, "", wxDefaultPosition, wxSize(200,300), [], wxCB_SIMPLE|wxCB_SORT )
    item4.AddWindow( item5, 0, wxGROW|wxALL, 5 )

    item6 = wxBoxSizer( wxVERTICAL )
    
    item7 = wxButton( parent, ID_ADD_TEAM, "Add", wxDefaultPosition, wxDefaultSize, 0 )
    item6.AddWindow( item7, 0, wxALIGN_CENTER|wxALL, 5 )

    item8 = wxButton( parent, ID_REMOVE_TEAM, "Remove", wxDefaultPosition, wxDefaultSize, 0 )
    item6.AddWindow( item8, 0, wxALIGN_CENTER|wxALL, 5 )

    item4.AddSizer( item6, 0, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 )

    item0.AddSizer( item4, 0, wxGROW|wxALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetAutoLayout( True )
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

ID_WEIGHTS_CAPTION = 10011
ID_WEIGHTS_COMBO = 10012
ID_ADD_WEIGHT = 10013
ID_REMOVE_WEIGHT = 10014
ID_ADD_STANDARD_WEIGHTS = 10015

def WizardWeightsPanel( parent, call_fit = True, set_sizer = True ):
    item0 = wxBoxSizer( wxVERTICAL )
    
    item1 = wxStaticText( parent, ID_TEXT, "Weight Classes", wxDefaultPosition, wxDefaultSize, 0 )
    item1.SetFont( wxFont( 16, wxSWISS, wxNORMAL, wxBOLD ) )
    item0.AddWindow( item1, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item2 = wxStaticText( parent, ID_WEIGHTS_CAPTION, "", wxDefaultPosition, wxDefaultSize, wxST_NO_AUTORESIZE )
    item0.AddWindow( item2, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item3 = wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL )
    item0.AddWindow( item3, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item4 = wxBoxSizer( wxHORIZONTAL )
    
    item5 = wxComboBox( parent, ID_WEIGHTS_COMBO, "", wxDefaultPosition, wxSize(200,300), [], wxCB_SIMPLE|wxCB_SORT )
    item4.AddWindow( item5, 0, wxGROW|wxALL, 5 )

    item6 = wxBoxSizer( wxVERTICAL )
    
    item7 = wxButton( parent, ID_ADD_WEIGHT, "Add", wxDefaultPosition, wxDefaultSize, 0 )
    item6.AddWindow( item7, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item8 = wxButton( parent, ID_REMOVE_WEIGHT, "Remove", wxDefaultPosition, wxDefaultSize, 0 )
    item6.AddWindow( item8, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item9 = wxButton( parent, ID_ADD_STANDARD_WEIGHTS, "Add Standard", wxDefaultPosition, wxDefaultSize, 0 )
    item6.AddWindow( item9, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item4.AddSizer( item6, 0, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 )

    item0.AddSizer( item4, 0, wxGROW|wxALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetAutoLayout( True )
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

ID_LAYOUT_CAPTION = 10016
ID_LAYOUT_LIST = 10017
ID_LAYOUT_TEXT = 10018

def WizardLayoutPanel( parent, call_fit = True, set_sizer = True ):
    item0 = wxBoxSizer( wxVERTICAL )
    
    item1 = wxStaticText( parent, ID_TEXT, "Layout", wxDefaultPosition, wxDefaultSize, 0 )
    item1.SetFont( wxFont( 16, wxSWISS, wxNORMAL, wxBOLD ) )
    item0.AddWindow( item1, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item2 = wxStaticText( parent, ID_LAYOUT_CAPTION, "", wxDefaultPosition, wxDefaultSize, wxST_NO_AUTORESIZE )
    item0.AddWindow( item2, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item3 = wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL )
    item0.AddWindow( item3, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item4 = wxBoxSizer( wxHORIZONTAL )
    
    item6 = wxStaticBox( parent, -1, "Available brackets" )
    item5 = wxStaticBoxSizer( item6, wxHORIZONTAL )
    
    item7 = wxListBox( parent, ID_LAYOUT_LIST, wxDefaultPosition, wxSize(180,200), [], wxLB_SINGLE|wxLB_SORT )
    item5.AddWindow( item7, 0, wxGROW|wxALL, 5 )

    item4.AddSizer( item5, 0, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 )

    item9 = wxStaticBox( parent, -1, "Description" )
    item8 = wxStaticBoxSizer( item9, wxHORIZONTAL )
    
    item10 = wxTextCtrl( parent, ID_LAYOUT_TEXT, "", wxDefaultPosition, wxSize(250,40), wxTE_MULTILINE|wxTE_READONLY )
    item8.AddWindow( item10, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item4.AddSizer( item8, 0, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 )

    item0.AddSizer( item4, 0, wxGROW|wxALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetAutoLayout( True )
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

ID_FINISHED_CAPTION = 10019

def WizardFinishedPanel( parent, call_fit = True, set_sizer = True ):
    item0 = wxBoxSizer( wxVERTICAL )
    
    item1 = wxStaticText( parent, ID_TEXT, "Finished", wxDefaultPosition, wxDefaultSize, 0 )
    item1.SetFont( wxFont( 16, wxSWISS, wxNORMAL, wxBOLD ) )
    item0.AddWindow( item1, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item2 = wxStaticText( parent, ID_FINISHED_CAPTION, "", wxDefaultPosition, wxDefaultSize, wxST_NO_AUTORESIZE )
    item0.AddWindow( item2, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item3 = wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL )
    item0.AddWindow( item3, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    if set_sizer == True:
        parent.SetAutoLayout( True )
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

ID_WINNER_CHOICE = 10020
ID_SCOREPOINTS_CHECK = 10021
ID_RESULT_TYPE_RADIO = 10022
ID_RESULT_PANEL = 10023

def CreateMatchDialog( parent, call_fit = True, set_sizer = True ):
    item0 = wxBoxSizer( wxVERTICAL )
    
    item2 = wxStaticBox( parent, -1, "Winner" )
    item1 = wxStaticBoxSizer( item2, wxVERTICAL )
    
    item3 = wxChoice( parent, ID_WINNER_CHOICE, wxDefaultPosition, wxSize(150,-1), [], 0 )
    item1.AddWindow( item3, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item4 = wxCheckBox( parent, ID_SCOREPOINTS_CHECK, "Score team points", wxDefaultPosition, wxDefaultSize, 0 )
    item1.AddWindow( item4, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item0.AddSizer( item1, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item5 = wxRadioBox( parent, ID_RESULT_TYPE_RADIO, "Win type", wxDefaultPosition, wxDefaultSize, 
        ["None","Decision","Pin","Default","Bye"] , 2, wxRA_SPECIFY_ROWS )
    item0.AddWindow( item5, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item7 = wxStaticBox( parent, -1, "Result" )
    item6 = wxStaticBoxSizer( item7, wxVERTICAL )
    parent.result_sizer = item6
    
    item8 = wxPanel( parent, ID_RESULT_PANEL, wxDefaultPosition, wxSize(200,30), 0 )
    item6.AddWindow( item8, 0, wxALIGN_CENTER|wxALL, 5 )

    item0.AddSizer( item6, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item9 = wxBoxSizer( wxHORIZONTAL )
    
    item10 = wxButton( parent, wxID_OK, "OK", wxDefaultPosition, wxDefaultSize, 0 )
    item10.SetDefault()
    item9.AddWindow( item10, 0, wxALIGN_CENTER|wxALL, 5 )

    item11 = wxButton( parent, wxID_CANCEL, "Cancel", wxDefaultPosition, wxDefaultSize, 0 )
    item9.AddWindow( item11, 0, wxALIGN_CENTER|wxALL, 5 )

    item0.AddSizer( item9, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    if set_sizer == True:
        parent.SetAutoLayout( True )
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

ID_TYPE_RADIOBOX = 10024
ID_WEIGHTS_LIST = 10025
ID_ROUNDS_LIST = 10026

def CreatePrintDialog( parent, call_fit = True, set_sizer = True ):
    item0 = wxBoxSizer( wxVERTICAL )
    
    item1 = wxRadioBox( parent, ID_TYPE_RADIOBOX, "Document", wxDefaultPosition, wxDefaultSize, 
        ["Brackets","Bouts","Places"] , 1, wxRA_SPECIFY_ROWS )
    item0.AddWindow( item1, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item2 = wxBoxSizer( wxHORIZONTAL )
    
    item4 = wxStaticBox( parent, -1, "Weights" )
    item3 = wxStaticBoxSizer( item4, wxVERTICAL )
    
    item5 = wxListBox( parent, ID_WEIGHTS_LIST, wxDefaultPosition, wxSize(200,100), [], wxLB_EXTENDED )
    item3.AddWindow( item5, 0, wxALIGN_CENTER|wxALL, 5 )

    item2.AddSizer( item3, 0, wxALIGN_CENTER|wxALL, 5 )

    item7 = wxStaticBox( parent, -1, "Rounds" )
    item6 = wxStaticBoxSizer( item7, wxVERTICAL )
    
    item8 = wxListBox( parent, ID_ROUNDS_LIST, wxDefaultPosition, wxSize(200,100), [], wxLB_EXTENDED )
    item8.Enable(False)
    item6.AddWindow( item8, 0, wxALIGN_CENTER|wxALL, 5 )

    item2.AddSizer( item6, 0, wxALIGN_CENTER|wxALL, 5 )

    item0.AddSizer( item2, 0, wxALIGN_CENTER|wxALL, 5 )

    item9 = wxBoxSizer( wxHORIZONTAL )
    
    item10 = wxButton( parent, wxID_OK, "OK", wxDefaultPosition, wxDefaultSize, 0 )
    item10.SetDefault()
    item9.AddWindow( item10, 0, wxALIGN_CENTER|wxALL, 5 )

    item11 = wxButton( parent, wxID_CANCEL, "Cancel", wxDefaultPosition, wxDefaultSize, 0 )
    item9.AddWindow( item11, 0, wxALIGN_CENTER|wxALL, 5 )

    item0.AddSizer( item9, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    if set_sizer == True:
        parent.SetAutoLayout( True )
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

ID_POINTADJUST_TEXT = 10027
ID_POINTADJUST_SPIN = 10028
ID_WRESTLERS_LIST = 10029

def CreateTeamDialog( parent, call_fit = True, set_sizer = True ):
    item0 = wxBoxSizer( wxVERTICAL )
    
    item2 = wxStaticBox( parent, -1, "Point adjustment" )
    item1 = wxStaticBoxSizer( item2, wxHORIZONTAL )
    
    item3 = wxTextCtrl( parent, ID_POINTADJUST_TEXT, "", wxDefaultPosition, wxSize(40,-1), wxTE_READONLY )
    item1.AddWindow( item3, 0, wxALIGN_CENTER|wxLEFT|wxTOP|wxBOTTOM, 5 )

    item4 = wxSpinButton( parent, ID_POINTADJUST_SPIN, wxDefaultPosition, wxSize(-1,22), wxSP_WRAP )
    item4.SetRange( 0, 100 )
    item4.SetValue( 0 )
    item1.AddWindow( item4, 0, wxALIGN_CENTER|wxRIGHT|wxTOP|wxBOTTOM, 5 )

    item0.AddSizer( item1, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item6 = wxStaticBox( parent, -1, "Text" )
    item5 = wxStaticBoxSizer( item6, wxVERTICAL )
    
    item7 = wxListCtrl( parent, ID_WRESTLERS_LIST, wxDefaultPosition, wxSize(200,120), wxLC_REPORT|wxSUNKEN_BORDER )
    item5.AddWindow( item7, 0, wxALIGN_CENTER|wxALL, 5 )

    item0.AddSizer( item5, 0, wxALIGN_CENTER|wxALL, 5 )

    item8 = wxBoxSizer( wxHORIZONTAL )
    
    item9 = wxButton( parent, wxID_OK, "OK", wxDefaultPosition, wxDefaultSize, 0 )
    item9.SetDefault()
    item8.AddWindow( item9, 0, wxALIGN_CENTER|wxALL, 5 )

    item10 = wxButton( parent, wxID_CANCEL, "Cancel", wxDefaultPosition, wxDefaultSize, 0 )
    item8.AddWindow( item10, 0, wxALIGN_CENTER|wxALL, 5 )

    item0.AddSizer( item8, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    if set_sizer == True:
        parent.SetAutoLayout( True )
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

ID_RESULTS_LIST = 10030

def CreateFastFallDialog( parent, call_fit = True, set_sizer = True ):
    item0 = wxBoxSizer( wxVERTICAL )
    
    item1 = wxListCtrl( parent, ID_RESULTS_LIST, wxDefaultPosition, wxSize(450,300), wxLC_REPORT|wxSUNKEN_BORDER )
    item0.AddWindow( item1, 0, wxALIGN_CENTER|wxALL, 5 )

    item2 = wxBoxSizer( wxHORIZONTAL )
    
    item3 = wxButton( parent, wxID_OK, "OK", wxDefaultPosition, wxDefaultSize, 0 )
    item3.SetDefault()
    item2.AddWindow( item3, 0, wxALIGN_CENTER|wxALL, 5 )

    item0.AddSizer( item2, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    if set_sizer == True:
        parent.SetAutoLayout( True )
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

ID_STATICBITMAP = 10031

def CreateAboutDialog( parent, call_fit = True, set_sizer = True ):
    item0 = wxBoxSizer( wxVERTICAL )
    
    item1 = wxStaticBitmap( parent, ID_STATICBITMAP, LogoBitmaps( 0 ), wxDefaultPosition, wxDefaultSize )
    item0.AddWindow( item1, 0, wxALIGN_CENTER|wxALL, 5 )

    item2 = wxStaticText( parent, ID_TEXT, 
        "Wrestling Nerd 3.0\n"
        "Written by Peter Parente\n"
        "\n"
        "Thanks to Jakob Fischer for the font used in the Wrestling Nerd logo.\n"
        "\n"
        "Copyright 2003 Peter Parente under the MIT License\n"
        "See the included LICENSE.txt file for restrictions on the use and distribution of this software.",
        wxDefaultPosition, wxDefaultSize, 0 )
    item2.SetBackgroundColour( wxWHITE )
    item0.AddWindow( item2, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    if set_sizer == True:
        parent.SetAutoLayout( True )
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

ID_NEW_MENU = 10032
ID_OPEN_MENU = 10033
ID_MENU = 10034
ID_SAVE_MENU = 10035
ID_SAVEAS_MENU = 10036
ID_PRINT_MENU = 10037
ID_EXIT_MENU = 10038
ID_FILE_MENU = 10039
ID_FASTFALL_MENU = 10040
ID_NUMBOUTS_MENU = 10041
ID_SCOREWIN_MENU = 10042
ID_QUERY_MENU = 10043
ID_ABOUT_MENU = 10044
ID_HELP_MENU = 10045

def CreateMenuBar():
    item0 = wxMenuBar()
    
    item1 = wxMenu()
    item1.Append( ID_NEW_MENU, "&New...\tCtrl-N", "" )
    item1.Append( ID_OPEN_MENU, "&Open...\tCtrl-O", "" )
    item1.AppendSeparator()
    item1.Append( ID_SAVE_MENU, "&Save\tCtrl-S", "" )
    item1.Append( ID_SAVEAS_MENU, "Save &as...\tShift-Ctrl-S", "" )
    item1.AppendSeparator()
    item1.Append( ID_PRINT_MENU, "&Print...\tCtrl-P", "" )
    item1.AppendSeparator()
    item1.Append( ID_EXIT_MENU, "E&xit", "" )
    item0.Append( item1, "&File" )
    
    item2 = wxMenu()
    item2.Append( ID_FASTFALL_MENU, "&Fast fall...\tCtrl-F", "" )
    item2.Append( ID_NUMBOUTS_MENU, "&Bout count...\tCtrl-B", "" )
    item2.AppendSeparator()
    item2.Append( ID_SCOREWIN_MENU, "Score &window...\tCtrl-W", "" )
    item0.Append( item2, "&Query" )
    
    item3 = wxMenu()
    item3.Append( ID_ABOUT_MENU, "&About", "" )
    item0.Append( item3, "&Help" )
    
    return item0

# Toolbar functions

# Bitmap functions

ID_LOGO = 10046

def LogoBitmaps( index ):
    if (index == 0) or (index == ID_LOGO):
        return wxImage( "WrestlingNerd_wdr/LogoBitmaps_0.png", wxBITMAP_TYPE_PNG ).ConvertToBitmap()
    return wxNullBitmap

# End of generated file
