# -*- coding: iso-8859-15 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: WrestlingNerd.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxWindows' modules
import wx
import wx.grid

# Custom source
ID_DELETE_MATCH_MENU = wx.NewId()
ID_DELETEALL_MATCH_MENU = wx.NewId()
ID_MOVEIN_MATCH_MENU = wx.NewId()

ID_DELETE_SEED_MENU = wx.NewId()
ID_DELETEMOVEUP_SEED_MENU = wx.NewId()
ID_INSERTMOVEDOWN_SEED_MENU = wx.NewId()
ID_SETLAST_SEED_MENU = wx.NewId()
ID_SWAPUP_SEED_MENU = wx.NewId()
ID_SWAPDOWN_SEED_MENU = wx.NewId()
ID_SWAPTO_SEED_MENU = wx.NewId()

start_caption = '''Welcome to the new tournament wizard.

Use the Next and Previous buttons below to move through the steps necessary to create a new tournament. Directions are given at the start of each step.

Press the Next button to begin.
'''
name_caption = '''First, enter a name for the tournament.
  
Press the Next button when you are done.
'''
teams_caption = '''Enter the names of all the teams in the tournament in the box below. Type the name of the team and then press the Add button. Remove an incorrect team by selecting it and pressing Remove. Pressing Enter after typing a team name is a shortcut for clicking the Add button.

Press the Next button when you are done.  
'''

weights_caption = '''Enter the weight classes in the tournament. Type the name and use the Add and Remove buttons or Enter key as you did to enter the teams. Pressing the Add Standard button will enter all of the U.S. standard weight classes for you.
  
Press the Next button when you are done.
'''
layout_caption = '''Select the layout for this tournament. Choose a layout name from the box on the left. A description of the layout appears to the right.
  
Press the Next button when you are done.
'''
finished_caption = '''You have finished creating a new tournament. Press the Previous button to go back and make changes. When you are satisfied, press the Finish button to complete this wizard.'''

# Window functions

ID_WEIGHTS_CHOICE = 10000
ID_TEAMS_LIST = 10001

def CreateSidePanel( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item2 = wx.StaticBox( parent, -1, "Weight" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    
    item3 = wx.Choice( parent, ID_WEIGHTS_CHOICE, wx.DefaultPosition, [100,-1], [], 0 )
    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item5 = wx.StaticBox( parent, -1, "Scores" )
    item4 = wx.StaticBoxSizer( item5, wx.VERTICAL )
    
    item6 = wx.ListCtrl( parent, ID_TEAMS_LIST, wx.DefaultPosition, [180,300], wx.LC_REPORT|wx.SUNKEN_BORDER )
    item4.Add( item6, 0, wx.GROW|wx.ALL, 5 )

    item0.Add( item4, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TEXT = 10002
ID_START_CAPTION = 10003
ID_LINE = 10004

def WizardStartPanel( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item1 = wx.StaticText( parent, ID_TEXT, "New Tournament", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.SetFont( wx.Font( 16, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item0.Add( item1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item2 = wx.StaticText( parent, ID_START_CAPTION, "", wx.DefaultPosition, [-1,80], wx.ST_NO_AUTORESIZE )
    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item0.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_NAME_CAPTION = 10005
ID_NAME_TEXT = 10006

def WizardNamePanel( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item1 = wx.StaticText( parent, ID_TEXT, "Name", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.SetFont( wx.Font( 16, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item0.Add( item1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item2 = wx.StaticText( parent, ID_NAME_CAPTION, "", wx.DefaultPosition, wx.DefaultSize, wx.ST_NO_AUTORESIZE )
    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item0.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item4 = wx.StaticText( parent, ID_TEXT, "Tournament name", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item4, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item5 = wx.TextCtrl( parent, ID_NAME_TEXT, "", wx.DefaultPosition, [200,-1], 0 )
    item0.Add( item5, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TEAMS_CAPTION = 10007
ID_TEAMS_TEXT = 10008
ID_ADD_TEAM = 10009
ID_REMOVE_TEAM = 10010

def WizardTeamsPanel( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item1 = wx.StaticText( parent, ID_TEXT, "Teams", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.SetFont( wx.Font( 16, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item0.Add( item1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item2 = wx.StaticText( parent, ID_TEAMS_CAPTION, "", wx.DefaultPosition, [-1,70], wx.ST_NO_AUTORESIZE )
    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item0.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item4 = wx.BoxSizer( wx.HORIZONTAL )
    
    item5 = wx.BoxSizer( wx.VERTICAL )
    
    item6 = wx.TextCtrl( parent, ID_TEAMS_TEXT, "", wx.DefaultPosition, [200,-1], wx.TE_PROCESS_ENTER )
    item5.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item7 = wx.ListBox( parent, ID_TEAMS_LIST, wx.DefaultPosition, [80,250], [], wx.LB_SINGLE )
    item5.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item4.Add( item5, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item8 = wx.BoxSizer( wx.VERTICAL )
    
    item9 = wx.Button( parent, ID_ADD_TEAM, "Add", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item10 = wx.Button( parent, ID_REMOVE_TEAM, "Remove", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item4.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 5 )

    item0.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_WEIGHTS_CAPTION = 10011
ID_WEIGHTS_TEXT = 10012
ID_WEIGHTS_LIST = 10013
ID_ADD_WEIGHT = 10014
ID_REMOVE_WEIGHT = 10015
ID_ADD_STANDARD_WEIGHTS = 10016

def WizardWeightsPanel( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item1 = wx.StaticText( parent, ID_TEXT, "Weight Classes", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.SetFont( wx.Font( 16, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item0.Add( item1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item2 = wx.StaticText( parent, ID_WEIGHTS_CAPTION, "", wx.DefaultPosition, [-1,70], wx.ST_NO_AUTORESIZE )
    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item0.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item4 = wx.BoxSizer( wx.HORIZONTAL )
    
    item5 = wx.BoxSizer( wx.VERTICAL )
    
    item6 = wx.TextCtrl( parent, ID_WEIGHTS_TEXT, "", wx.DefaultPosition, [200,-1], wx.TE_PROCESS_ENTER )
    item5.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item7 = wx.ListBox( parent, ID_WEIGHTS_LIST, wx.DefaultPosition, [80,250], [], wx.LB_SINGLE )
    item5.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item4.Add( item5, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item8 = wx.BoxSizer( wx.VERTICAL )
    
    item9 = wx.Button( parent, ID_ADD_WEIGHT, "Add", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item10 = wx.Button( parent, ID_REMOVE_WEIGHT, "Remove", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item11 = wx.Button( parent, ID_ADD_STANDARD_WEIGHTS, "Add Standard", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item4.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 5 )

    item0.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_LAYOUT_CAPTION = 10017
ID_LAYOUT_LIST = 10018
ID_LAYOUT_TEXT = 10019

def WizardLayoutPanel( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item1 = wx.StaticText( parent, ID_TEXT, "Layout", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.SetFont( wx.Font( 16, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item0.Add( item1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item2 = wx.StaticText( parent, ID_LAYOUT_CAPTION, "", wx.DefaultPosition, [-1,60], wx.ST_NO_AUTORESIZE )
    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item0.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item4 = wx.BoxSizer( wx.HORIZONTAL )
    
    item6 = wx.StaticBox( parent, -1, "Available brackets" )
    item5 = wx.StaticBoxSizer( item6, wx.HORIZONTAL )
    
    item7 = wx.ListBox( parent, ID_LAYOUT_LIST, wx.DefaultPosition, [180,200], [], wx.LB_SINGLE|wx.LB_SORT )
    item5.Add( item7, 0, wx.GROW|wx.ALL, 5 )

    item4.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 5 )

    item9 = wx.StaticBox( parent, -1, "Description" )
    item8 = wx.StaticBoxSizer( item9, wx.HORIZONTAL )
    
    item10 = wx.TextCtrl( parent, ID_LAYOUT_TEXT, "", wx.DefaultPosition, [250,40], wx.TE_MULTILINE|wx.TE_READONLY )
    item8.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item4.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 5 )

    item0.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_FINISHED_CAPTION = 10020

def WizardFinishedPanel( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item1 = wx.StaticText( parent, ID_TEXT, "Finished", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.SetFont( wx.Font( 16, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item0.Add( item1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item2 = wx.StaticText( parent, ID_FINISHED_CAPTION, "", wx.DefaultPosition, [-1,40], wx.ST_NO_AUTORESIZE )
    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item0.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_WINNER_LIST = 10021
ID_SCOREPOINTS_CHECK = 10022
ID_RESULT_TYPE_RADIO = 10023
ID_RESULT_PANEL = 10024
wxID_OK = 5100
wxID_CANCEL = 5101

def CreateMatchDialog( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item2 = wx.StaticBox( parent, -1, "Winner" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    
    item3 = wx.ListBox( parent, ID_WINNER_LIST, wx.DefaultPosition, [60,30], [], wx.LB_SINGLE )
    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item4 = wx.CheckBox( parent, ID_SCOREPOINTS_CHECK, "Score team points", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item4, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item5 = wx.RadioBox( parent, ID_RESULT_TYPE_RADIO, "Win type", wx.DefaultPosition, wx.DefaultSize, 
        ["None","Decision","Pin","Default","Bye"] , 2, wx.RA_SPECIFY_ROWS )
    item0.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item7 = wx.StaticBox( parent, -1, "Result" )
    item6 = wx.StaticBoxSizer( item7, wx.VERTICAL )
    parent.result_sizer = item6
    
    item8 = wx.Panel( parent, ID_RESULT_PANEL, wx.DefaultPosition, [200,30], 0 )
    item6.Add( item8, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item9 = wx.BoxSizer( wx.HORIZONTAL )
    
    item10 = wx.Button( parent, wxID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item10.SetDefault()
    item9.Add( item10, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item11 = wx.Button( parent, wxID_CANCEL, "Cancel", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.Add( item11, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item9, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TYPE_RADIOBOX = 10025
ID_ROUNDS_LIST = 10026
wxID_OK = 5100
wxID_CANCEL = 5101

def CreatePrintDialog( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item1 = wx.RadioBox( parent, ID_TYPE_RADIOBOX, "Document", wx.DefaultPosition, wx.DefaultSize, 
        ["&Brackets","B&outs","&Scores","&Places"] , 1, wx.RA_SPECIFY_ROWS )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item2 = wx.BoxSizer( wx.HORIZONTAL )
    
    item4 = wx.StaticBox( parent, -1, "Weights" )
    item3 = wx.StaticBoxSizer( item4, wx.VERTICAL )
    
    item5 = wx.ListBox( parent, ID_WEIGHTS_LIST, wx.DefaultPosition, [200,200], [], wx.LB_EXTENDED )
    item3.Add( item5, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item2.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item7 = wx.StaticBox( parent, -1, "Rounds" )
    item6 = wx.StaticBoxSizer( item7, wx.VERTICAL )
    
    item8 = wx.ListBox( parent, ID_ROUNDS_LIST, wx.DefaultPosition, [200,200], [], wx.LB_EXTENDED )
    item8.Enable(False)
    item6.Add( item8, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item2.Add( item6, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item2, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item9 = wx.BoxSizer( wx.HORIZONTAL )
    
    item10 = wx.Button( parent, wxID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item10.SetDefault()
    item9.Add( item10, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item11 = wx.Button( parent, wxID_CANCEL, "Cancel", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.Add( item11, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item9, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_POINTADJUST_TEXT = 10027
ID_POINTADJUST_SPIN = 10028
ID_WRESTLERS_LIST = 10029
wxID_OK = 5100
wxID_CANCEL = 5101

def CreateTeamDialog( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item2 = wx.StaticBox( parent, -1, "Point adjustment" )
    item1 = wx.StaticBoxSizer( item2, wx.HORIZONTAL )
    
    item3 = wx.TextCtrl( parent, ID_POINTADJUST_TEXT, "", wx.DefaultPosition, [60,-1], wx.TE_READONLY )
    item1.Add( item3, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item4 = wx.SpinButton( parent, ID_POINTADJUST_SPIN, wx.DefaultPosition, [20,22], wx.SP_WRAP )
    item4.SetRange( 0, 100 )
    item4.SetValue( 0 )
    item1.Add( item4, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item6 = wx.StaticBox( parent, -1, "Wrestlers" )
    item5 = wx.StaticBoxSizer( item6, wx.VERTICAL )
    
    item7 = wx.ListCtrl( parent, ID_WRESTLERS_LIST, wx.DefaultPosition, [200,200], wx.LC_REPORT|wx.SUNKEN_BORDER )
    item5.Add( item7, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item5, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item8 = wx.BoxSizer( wx.HORIZONTAL )
    
    item9 = wx.Button( parent, wxID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.SetDefault()
    item8.Add( item9, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item10 = wx.Button( parent, wxID_CANCEL, "Cancel", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.Add( item10, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item8, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_RESULTS_LIST = 10030
wxID_OK = 5100

def CreateFastFallDialog( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item1 = wx.ListCtrl( parent, ID_RESULTS_LIST, wx.DefaultPosition, [450,300], wx.LC_REPORT|wx.SUNKEN_BORDER )
    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item2 = wx.BoxSizer( wx.HORIZONTAL )
    
    item3 = wx.Button( parent, wxID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.SetDefault()
    item2.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item2, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_STATICBITMAP = 10031

def CreateAboutDialog( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item1 = wx.StaticBitmap( parent, ID_STATICBITMAP, LogoBitmaps( 0 ), wx.DefaultPosition, wx.DefaultSize )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item2 = wx.StaticText( parent, ID_TEXT, 
        "Dedicated to my father, my mother, and my brother, who all know the glory and pain of wrestling.\n"
        "Special thanks to David Greenleaf, the very first wrestling nerd.\n"
        "\n"
        "Copyright (c) 2003, 2004, 2005 Peter Parente under the terms of the MIT public license.\n"
        "\n"
        "See the included LICENSE.txt file included with this software for restrictions on the use and\n"
        "distribution of this software.",
        wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.SetBackgroundColour( wx.WHITE )
    item0.Add( item2, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_SCORES_LIST = 10032

def CreateScoreFrame( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 2, 0, 0 )
    item0.AddGrowableCol( 0 )
    item0.AddGrowableRow( 0 )
    
    item1 = wx.ListCtrl( parent, ID_SCORES_LIST, wx.DefaultPosition, [160,120], wx.LC_REPORT|wx.SUNKEN_BORDER )
    item1.SetFont( wx.Font( 14, wx.SWISS, wx.NORMAL, wx.NORMAL ) )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TEAMS_CHOICE = 10033
wxID_OK = 5100
wxID_CANCEL = 5101

def CreateTeamSpellingDialog( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item1 = wx.StaticText( parent, ID_TEXT, "Current name", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item1, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item2 = wx.Choice( parent, ID_TEAMS_CHOICE, wx.DefaultPosition, [200,-1], [], 0 )
    item0.Add( item2, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item3 = wx.StaticText( parent, ID_TEXT, "New name", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item3, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item4 = wx.TextCtrl( parent, ID_NAME_TEXT, "", wx.DefaultPosition, [200,-1], 0 )
    item0.Add( item4, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item5 = wx.BoxSizer( wx.HORIZONTAL )
    
    item6 = wx.Button( parent, wxID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.SetDefault()
    item5.Add( item6, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item7 = wx.Button( parent, wxID_CANCEL, "Cancel", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.Add( item7, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item5, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_WRESTLERS_CHOICE = 10034
wxID_OK = 5100
wxID_CANCEL = 5101

def CreateWrestlerSpellingDialog( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item1 = wx.StaticText( parent, ID_TEXT, "Team", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item1, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item2 = wx.Choice( parent, ID_TEAMS_CHOICE, wx.DefaultPosition, [200,-1], [], 0 )
    item0.Add( item2, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item3 = wx.StaticText( parent, ID_TEXT, "Current wrestler name", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item3, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item4 = wx.Choice( parent, ID_WRESTLERS_CHOICE, wx.DefaultPosition, [200,-1], [], 0 )
    item0.Add( item4, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item5 = wx.StaticText( parent, ID_TEXT, "New wrestler name", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item5, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item6 = wx.TextCtrl( parent, ID_NAME_TEXT, "", wx.DefaultPosition, [200,-1], 0 )
    item0.Add( item6, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item7 = wx.BoxSizer( wx.HORIZONTAL )
    
    item8 = wx.Button( parent, wxID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.SetDefault()
    item7.Add( item8, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item9 = wx.Button( parent, wxID_CANCEL, "Cancel", wx.DefaultPosition, wx.DefaultSize, 0 )
    item7.Add( item9, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item7, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

ID_NEW_MENU = 10035
ID_OPEN_MENU = 10036
ID_MENU = 10037
ID_SAVE_MENU = 10038
ID_SAVEAS_MENU = 10039
ID_BACKUP_MENU = 10040
ID_EXPORT_MENU = 10041
ID_PRINT_MENU = 10042
ID_PRINTPREVIEW_MENU = 10043
ID_EXIT_MENU = 10044
ID_FILE_MENU = 10045
ID_FASTFALL_MENU = 10046
ID_NUMBOUTS_MENU = 10047
ID_SCOREWIN_MENU = 10048
ID_QUERY_MENU = 10049
ID_ADDTEAM_MENU = 10050
ID_REMOVETEAM_MENU = 10051
ID_TEAMSPELLING_MENU = 10052
ID_WRESTLERSPELLING_MENU = 10053
ID_TOURNAMENTNAME_MENU = 10054
ID_TOOLS_MENU = 10055
ID_ABOUT_MENU = 10056
ID_HELP_MENU = 10057

def CreateMenuBar():
    item0 = wx.MenuBar()
    
    item1 = wx.Menu()
    item1.Append( ID_NEW_MENU, "&New...\tCtrl-N", "" )
    item1.Append( ID_OPEN_MENU, "&Open...\tCtrl-O", "" )
    item1.AppendSeparator()
    item1.Append( ID_SAVE_MENU, "&Save\tCtrl-S", "" )
    item1.Append( ID_SAVEAS_MENU, "Save &as...\tShift-Ctrl-S", "" )
    item1.Append( ID_BACKUP_MENU, "&Backup...", "" )
    item1.AppendSeparator()
    item1.Append( ID_EXPORT_MENU, "Export...\tCtrl-E", "" )
    item1.AppendSeparator()
    item1.Append( ID_PRINT_MENU, "&Print...\tCtrl-P", "" )
    item1.Append( ID_PRINTPREVIEW_MENU, "Print previe&w...", "" )
    item1.AppendSeparator()
    item1.Append( ID_EXIT_MENU, "E&xit", "" )
    item0.Append( item1, "&File" )
    
    item2 = wx.Menu()
    item2.Append( ID_FASTFALL_MENU, "&Fast fall...\tCtrl-F", "" )
    item2.Append( ID_NUMBOUTS_MENU, "&Bout count...\tCtrl-B", "" )
    item2.AppendSeparator()
    item2.Append( ID_SCOREWIN_MENU, "Score &window...\tCtrl-W", "" )
    item0.Append( item2, "&Query" )
    
    item3 = wx.Menu()
    item3.Append( ID_ADDTEAM_MENU, "&Add a team...", "" )
    item3.Append( ID_REMOVETEAM_MENU, "&Remove a team...", "" )
    item3.AppendSeparator()
    item3.Append( ID_TEAMSPELLING_MENU, "Change team spelling...", "" )
    item3.Append( ID_WRESTLERSPELLING_MENU, "Change wrestler spelling...", "" )
    item3.Append( ID_TOURNAMENTNAME_MENU, "Change tournament name...", "" )
    item0.Append( item3, "&Tools" )
    
    item4 = wx.Menu()
    item4.Append( ID_ABOUT_MENU, "&About", "" )
    item0.Append( item4, "&Help" )
    
    return item0

# Toolbar functions

# Bitmap functions


def LogoBitmaps( index ):
    if index == 0:
        return wx.Image( "WrestlingNerd_wdr/LogoBitmaps_0.png", wx.BITMAP_TYPE_PNG ).ConvertToBitmap()
    return wx.NullBitmap

# End of generated file
